export interface User { id: string; email: string; username: string; phone: string | null; emailVerified: boolean; gender: 'MALE' | 'FEMALE' | 'OTHER' | null; birthDate: string | null; lastLoginAt: string | null; createdAt: string; }
export interface Profile { id: string; userId: string; firstName: string; lastName: string; fullName: string; avatarUrl: string | null; bio: string | null; timezone: string; language: string; theme: 'DARK'|'LIGHT'|'SYSTEM'; createdAt: string; updatedAt: string; }
export interface UserPreferences { id: string; userId: string; pomodoroFocusMinutes: number; pomodoroShortBreakMinutes: number; pomodoroLongBreakMinutes: number; pomodoroCyclesBeforeLongBreak: number; pomodoroAutoStartBreaks: boolean; pomodoroAutoStartFocus: boolean; pomodoroSoundEnabled: boolean; notifyTaskReminders: boolean; notifyEventReminders: boolean; notifyPomodoroEnd: boolean; notifyDailySummary: boolean; defaultTaskView: string; defaultTaskSort: string; showCompletedTasks: boolean; defaultCalendarView: string; weekStartsOn: string; aiContextEnabled: boolean; aiModel: string; compactMode: boolean; updatedAt: string; }
export interface AuthResponse { accessToken: string; tokenType: string; expiresIn: number; }
export interface UserResponse extends User { firstName: string; lastName: string; avatarUrl: string | null; bio: string | null; timezone: string; language: string; theme: 'DARK'|'LIGHT'|'SYSTEM'; pomodoroFocusMinutes: number; pomodoroShortBreakMinutes: number; pomodoroLongBreakMinutes: number; pomodoroCyclesBeforeLongBreak: number; pomodoroAutoStartBreaks: boolean; pomodoroAutoStartFocus: boolean; pomodoroSoundEnabled: boolean; notifyTaskReminders: boolean; notifyEventReminders: boolean; notifyPomodoroEnd: boolean; notifyDailySummary: boolean; defaultTaskView: string; defaultTaskSort: string; showCompletedTasks: boolean; defaultCalendarView: string; weekStartsOn: string; aiContextEnabled: boolean; aiModel: string; compactMode: boolean; }
export interface Tag { id: string; userId: string; name: string; color: string; createdAt: string; }
export interface Note { id: string; userId: string; title: string; content: string; plainTextContent: string; wordCount: number; readingTimeSeconds: number; pinned: boolean; deleted: boolean; deletedAt: string | null; version: number; syncStatus: 'PENDING'|'SYNCING'|'SYNCED'|'CONFLICT'; tags: Tag[]; createdAt: string; updatedAt: string; }
export type TaskStatus = 'TODO'|'IN_PROGRESS'|'ON_HOLD'|'DONE'|'CANCELLED';
export type TaskPriority = 'LOW'|'MEDIUM'|'HIGH'|'URGENT';
export interface Task { id: string; userId: string; parentTaskId: string | null; linkedEventId: string | null; title: string; description: string | null; status: TaskStatus; priority: TaskPriority; dueDate: string | null; dueTime: string | null; reminderAt: string | null; estimatedMinutes: number | null; actualMinutes: number; completedAt: string | null; position: number; deleted: boolean; deletedAt: string | null; version: number; syncStatus: 'PENDING'|'SYNCING'|'SYNCED'|'CONFLICT'; subtasks?: Task[]; createdAt: string; updatedAt: string; }
export interface CalendarEvent { id: string; userId: string; recurrenceParentId: string | null; title: string; description: string | null; location: string | null; startAt: string; endAt: string; allDay: boolean; color: string | null; recurrenceRule: string | null; recurrenceEndAt: string | null; reminderMinutes: number | null; deleted: boolean; deletedAt: string | null; version: number; syncStatus: 'PENDING'|'SYNCING'|'SYNCED'|'CONFLICT'; createdAt: string; updatedAt: string; }
export type PomodoroType = 'FOCUS'|'SHORT_BREAK'|'LONG_BREAK';
export interface PomodoroSession { id: string; userId: string; taskId: string | null; type: PomodoroType; plannedDurationSeconds: number; actualDurationSeconds: number | null; interrupted: boolean; interruptReason: string | null; focusMinutesSetting: number; shortBreakMinutesSetting: number; longBreakMinutesSetting: number; startedAt: string; endedAt: string | null; completed: boolean; actualMinutes: number | null; createdAt: string; }
export interface PomodoroStats { completedFocusSessionsToday: number; totalFocusMinutesToday: number; totalFocusSecondsToday: number; }
export interface Conversation { id: string; userId: string; title: string | null; archived: boolean; messages?: Message[]; createdAt: string; updatedAt: string; }
export interface MessageActionBlock { action: 'CREATE_TASK'|'CREATE_NOTE'|'ADD_EVENT'; title: string; content?: string; priority?: string; dueDate?: string; start?: string; durationMinutes?: number; }
export interface Message { id: string; conversationId: string; role: 'USER'|'ASSISTANT'; content: string; actionBlock: MessageActionBlock | null; tokenCount: number | null; createdAt: string; }
export interface SearchResult { id: string; type: 'NOTE'|'TASK'|'EVENT'|'CONVERSATION'; title: string; snippet: string | null; updatedAt: string; }
export interface SearchResponse { results: SearchResult[]; total: number; query: string; }
export interface ApiResponse<T> { success: boolean; data: T | null; message: string | null; errorCode: string | null; timestamp: string; }
export interface PagedResponse<T> { content: T[]; totalElements: number; totalPages: number; size: number; page: number; first: boolean; last: boolean; }
export interface DeltaSyncResponse { notes: Note[]; tasks: Task[]; events: CalendarEvent[]; pomodoroSessions: PomodoroSession[]; nextCursor: string | null; hasMore: boolean; syncedAt: string; totalChanges: number; }
export interface DeviceResponse { id: string; deviceId: string; deviceName: string | null; platform: 'ANDROID'|'IOS'|'DESKTOP'|'WEB'|null; lastSeenAt: string; createdAt: string; }
